### ISSUE TITLE
T2InfantCatalogEval evaluated too quickly, T2CatalogMatch did not complete

### ISSUE THREAD

**Issue by wombaugh** [AmpelProject/Ampel-HU-astro#6]
T2InfantCatalogEval is chained to T2CatalogMatch, but it appears it is run over and over immediately until the max number of iterations has been tried, while T2CatalogMatch can take some time to complete.

An example is ZTF22aafrjnw which was first detected 2022-04-14T09:13:45, at which point the T2 tickets were generated. T2InfantCatalogEval had all its attempts completed by 2022-04-14T09:14:53 and was set to a failed state -8 (so a min after first detection) in run 424330. Meanwhile, the  T2CatalogMatch result which would have been needed to complete T2InfantCatalogEval was nut run until 2022-04-14T10:50:06 (run 424446). 

I do not know what happened here. The catalog server might have been overloaded. In any case, should there be some exponential waiting time before a new attempt at running a chained T2? Or in some other way make sure that the required units at least have had a chance to complete?

**Comment by wombaugh** [comment]
Solution through T2Worker variants from Valery:
"One needs to define a standard t2 worker that only processes DocumentCode.NEW documents.
Then another worker (or many) should target DocumentCode.T2_PENDING_DEPENDENCY documents.
The matching query of the second category of workers should be restricted, by requiring a configurable delay between now and the latest meta.ts timestamp."

**Comment by wombaugh** [comment]
Added functionality of https://github.com/AmpelProject/Ampel-core/commit/816c70f397b4100530ac32a77e367349b1679e25 could be used to fix this as above.

**Comment by vbrinnel** [comment]
Yes, so this should be resolvable using the new parameter `min_doc_age`. You would need to define processes with:
- One or many t2 workers with `code_match = DocumentCode.NEW`.
- One or many t2 workers with `code_match = DocumentCode.T2_PENDING_DEPENDENCY`, `min_doc_age = <some value in seconds>`, `max_retry = <integer number>`

Make sure `min_doc_age` times `max_retry` is larger than the expected "time to complete" of all dependencies combined (including time-length of potential downtimes of the catalog server)
